---
title: "plotly examples"
output: 
  html_document:
    toc: true
    toc_float: true
    code_folding: hide
---

# Loading the data

look at the airbnb data in NYC.

```{r set up}
library(tidyverse)
library(p8105.datasets)
library(plotly)
```
```{r airbnb and establish a subset---which means we do not need this data set too huge because this will make the webpage too big and slow maybe several thousands are okey but not over 10 thousands}
data("nyc_airbnb")

nyc_airbnb = 
  nyc_airbnb |> 
  mutate(rating = review_scores_location / 2) |>
  select(
    neighbourhood_group, neighbourhood, rating, price, room_type, lat, long) |>
  filter(
    !is.na(rating), 
    neighbourhood_group == "Manhattan",
    room_type == "Entire home/apt",
    price %in% 100:500)
```

# Plotly plots

## Scatter plot
```{r scatter plot}
nyc_airbnb |>
  mutate(text_label = str_c("Price: $", price, "\nRating: ", rating)) |> 
  plot_ly(
    x = ~lat, y = ~long, type = "scatter", mode = "markers",
    color = ~price, text = ~text_label, alpha = 0.5)
```

## Box plot
```{r box plot}
nyc_airbnb |> 
  mutate(neighbourhood = fct_reorder(neighbourhood, price)) |> 
  plot_ly(y = ~price, color = ~neighbourhood, type = "box", colors = "viridis")
```
## bar plot
```{r bar plot}
nyc_airbnb |> 
  count(neighbourhood) |> 
  mutate(neighbourhood = fct_reorder(neighbourhood, n)) |> 
  plot_ly(x = ~neighbourhood, y = ~n, color = ~neighbourhood, type = "bar", colors = "viridis")
```

